### ISSUE TITLE
running tests with many failed on node.js 10.38

### ISSUE THREAD

**Issue by smartmouse** [indutny/tls.js#9]
Is this an issue with the unit tests? or some security issue on server.?
Thanks in advance.   

tls1.2
        TLS_RSA_WITH_AES_256_CBC_SHA
          ✓ should connect to OpenSSL server (95ms)
          1) should accept connections from OpenSSL client
        TLS_RSA_WITH_AES_128_CBC_SHA
          2) should connect to OpenSSL server
          3) should accept connections from OpenSSL client
        TLS_RSA_WITH_AES_256_CBC_SHA256
          4) should connect to OpenSSL server
          5) should accept connections from OpenSSL client
        TLS_RSA_WITH_AES_128_CBC_SHA256
          6) should connect to OpenSSL server
          7) should accept connections from OpenSSL client
        TLS_RSA_WITH_DES_CBC_SHA
          8) should connect to OpenSSL server
          9) should accept connections from OpenSSL client
        TLS_RSA_WITH_3DES_EDE_CBC_SHA
          10) should connect to OpenSSL server
          11) should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_MD5
          12) should connect to OpenSSL server
          13) should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_SHA
          14) should connect to OpenSSL server
          15) should accept connections from OpenSSL client
        TLS_RSA_WITH_NULL_SHA
          16) should connect to OpenSSL server
          17) should accept connections from OpenSSL client
        TLS_RSA_WITH_IDEA_CBC_SHA
          18) should connect to OpenSSL server
          19) should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          20) should connect to OpenSSL server
          21) should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
          22) should connect to OpenSSL server
          23) should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
          24) should connect to OpenSSL server
          25) should accept connections from OpenSSL client
      tls1.1
        TLS_RSA_WITH_AES_256_CBC_SHA
          26) should connect to OpenSSL server
          27) should accept connections from OpenSSL client
        TLS_RSA_WITH_AES_128_CBC_SHA
          28) should connect to OpenSSL server
          29) should accept connections from OpenSSL client
        TLS_RSA_WITH_DES_CBC_SHA
          30) should connect to OpenSSL server
          31) should accept connections from OpenSSL client
        TLS_RSA_WITH_3DES_EDE_CBC_SHA
          32) should connect to OpenSSL server
          33) should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_MD5
          34) should connect to OpenSSL server
          35) should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_SHA
          36) should connect to OpenSSL server
          37) should accept connections from OpenSSL client
        TLS_RSA_WITH_NULL_SHA
          38) should connect to OpenSSL server
          39) should accept connections from OpenSSL client
        TLS_RSA_WITH_IDEA_CBC_SHA
          40) should connect to OpenSSL server
          41) should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          42) should connect to OpenSSL server
          43) should accept connections from OpenSSL client
      tls1.0
        TLS_RSA_WITH_AES_256_CBC_SHA
          44) should connect to OpenSSL server
          45) should accept connections from OpenSSL client
        TLS_RSA_WITH_AES_128_CBC_SHA
          46) should connect to OpenSSL server
          47) should accept connections from OpenSSL client
        TLS_RSA_WITH_DES_CBC_SHA
          48) should connect to OpenSSL server
          49) should accept connections from OpenSSL client
        TLS_RSA_WITH_3DES_EDE_CBC_SHA
          50) should connect to OpenSSL server
          51) should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_MD5
          52) should connect to OpenSSL server
          53) should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_SHA
          54) should connect to OpenSSL server
          55) should accept connections from OpenSSL client
        TLS_RSA_WITH_NULL_SHA
          56) should connect to OpenSSL server
          57) should accept connections from OpenSSL client
        TLS_RSA_WITH_IDEA_CBC_SHA
          58) should connect to OpenSSL server
          59) should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          60) should connect to OpenSSL server
          61) should accept connections from OpenSSL client

 46 passing (3s)
  61 failing

  1) tls.js/Socket interacting with OpenSSL tls1.2 TLS_RSA_WITH_AES_256_CBC_SHA should accept connections from OpenSSL client:
     Uncaught Error: Unknown method
      at new Credentials (crypto.js:104:20)
      at Object.exports.createCredentials (crypto.js:121:11)
      at Object.exports.connect (tls.js:1345:27)
      at Agent.createConnection (https.js:79:14)
      at Agent.createSocket (http.js:1294:16)
      at Agent.addRequest (http.js:1270:23)

**Comment by indutny** [comment]
Hello!

May I ask you to give a try to io.js or node.js v0.12? I think v0.10 does not support some of the ciphers properly.

**Comment by smartmouse** [comment]
sorry for delay -- with  0.12.7 node.js, the tests passed.
        ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_DES_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_3DES_EDE_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_MD5
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_NULL_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_IDEA_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
      tls1.0
        TLS_RSA_WITH_AES_256_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_AES_128_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_DES_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_3DES_EDE_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_MD5
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_RC4_128_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_NULL_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_RSA_WITH_IDEA_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          ✓ should connect to OpenSSL server
          ✓ should accept connections from OpenSSL client

  107 passing (2s)

However, when I install tls.js, there are some warnings, you may want to check them out.
but this issue can be closed now. Thanks .

make: Entering directory `/svt/nodebot/test/node_modules/tls.js/node_modules/prf/build'
  CXX(target) Release/obj.target/prf/src/prf.o
../src/prf.cc: In function ‘void prf::Generate(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/prf.cc:147:13: warning: name lookup of ‘i’ changed [enabled by default]
         if (i == 0) {
             ^
../src/prf.cc:101:12: warning:   matches this ‘i’ under ISO standard rules [enabled by default]
   for (int i = 0; pname != NULL; pname = next_name, i++, key += key_delta) {
            ^
../src/prf.cc:144:18: warning:   matches this ‘i’ under old rules [enabled by default]
         for (int i = 3; i < args.Length(); i++)
                  ^
  SOLINK_MODULE(target) Release/obj.target/prf.node
  COPY Release/prf.node
make: Leaving directory`/svt/nodebot/test/node_modules/tls.js/node_modules/p
